document.write( '<!-- Sidebar -->\n' );
document.write( '<ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\n' );
document.write( '\n' );
document.write( '    <!-- Sidebar - Brand -->\n' );
document.write( '    <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"index.html\">\n' );
document.write( '      <div class=\"sidebar-brand-icon rotate-n-15\">\n' );
document.write( '        <i class=\"fas fa-laugh-wink\"></i>\n' );
document.write( '      </div>\n' );
document.write( '      <div class=\"sidebar-brand-text mx-3\">Algorithm Visualiser</div>\n' );
document.write( '    </a>\n' );
document.write( '\n' );
document.write( '    <!-- Divider -->\n' );
document.write( '    <hr class=\"sidebar-divider my-0\">\n' );
document.write( '\n' );
document.write( '    <!-- Nav Item - Dashboard -->\n' );
document.write( '    <li class=\"nav-item active\">\n' );
document.write( '      <a class=\"nav-link\" href=\"https://blackrockdigital.github.io/startbootstrap-sb-admin-2/\">\n' );
document.write( '        <i class=\"fas fa-fw fa-tachometer-alt\"></i>\n' );
document.write( '        <span>Blackrock Dashboard Link</span></a>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <li class=\"nav-item active\">\n' );
document.write( '      <a class=\"nav-link\" href=\"https://sarahab23.github.io/algovisualiser/\">\n' );
document.write( '        <i class=\"fas fa-fw fa-home\"></i>\n' );
document.write( '        <span>Home</span></a>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <!-- Divider -->\n' );
document.write( '    <hr class=\"sidebar-divider\">\n' );
document.write( '\n' );
document.write( '    <!-- Heading -->\n' );
document.write( '    <div class=\"sidebar-heading\">\n' );
document.write( '      Algorithms\n' );
document.write( '    </div>\n' );
document.write( '    \n' );
document.write( '    <!-- Sorting-->\n' );
document.write( '    <li class=\"nav-item\">\n' );
document.write( '      <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseSort\" aria-expanded=\"true\" aria-controls=\"collapseSort\">\n' );
document.write( '        <i class=\"fas fa-fw fa-sort-amount-up-alt\"></i>\n' );
document.write( '        <span>Sorting Algorithms</span>\n' );
document.write( '      </a>\n' );
document.write( '      <div id=\"collapseSort\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\n' );
document.write( '        <div class=\"bg-white py-2 collapse-inner rounded\">\n' );
document.write( '           <!-- <h6 class=\"collapse-header\">Custom Components:</h6>  -->\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Quick Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Heap Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Merge Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Bubble Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Insetion Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Selection Sort</a>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <!-- Pathfinding -->\n' );
document.write( '\n' );
document.write( '    <li class=\"nav-item\">\n' );
document.write( '      <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePathfind\" aria-expanded=\"true\" aria-controls=\"collapsePathfind\">\n' );
document.write( '        <i class=\"fas fa-fw fa-compass\"></i>\n' );
document.write( '        <span>Pathfinding Algorithms</span>\n' );
document.write( '      </a>\n' );
document.write( '      <div id=\"collapsePathfind\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\n' );
document.write( '        <div class=\"bg-white py-2 collapse-inner rounded\">\n' );
document.write( '           <!-- <h6 class=\"collapse-header\">Custom Components:</h6>  -->\n' );
document.write( '          <a class=\"collapse-item\" href=\"pathfinding/blank.html\">Dijkstra</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"pathfinding/blank.html\">A* Search</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"pathfinding/blank.html\">DFS</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"pathfinding/blank.html\">BFS</a>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <!-- Divider -->\n' );
document.write( '    <hr class=\"sidebar-divider\">\n' );
document.write( '\n' );
document.write( '    <!-- Heading -->\n' );
document.write( '    <div class=\"sidebar-heading\">\n' );
document.write( '      Tutorials for building the site\n' );
document.write( '    </div>\n' );
document.write( '    \n' );
document.write( '    <!-- Sorting-->\n' );
document.write( '    <li class=\"nav-item\">\n' );
document.write( '      <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseSort\" aria-expanded=\"true\" aria-controls=\"collapseSort\">\n' );
document.write( '        <i class=\"fas fa-fw fa-sort-amount-up-alt\"></i>\n' );
document.write( '        <span>Sorting Algorithms</span>\n' );
document.write( '      </a>\n' );
document.write( '      <div id=\"collapseSort\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\n' );
document.write( '        <div class=\"bg-white py-2 collapse-inner rounded\">\n' );
document.write( '           <!-- <h6 class=\"collapse-header\">Custom Components:</h6>  -->\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Quick Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Heap Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Merge Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Bubble Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Insetion Sort</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"sorting/blank.html\">Selection Sort</a>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <!-- Pathfinding -->\n' );
document.write( '\n' );
document.write( '    <li class=\"nav-item\">\n' );
document.write( '      <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePathfind\" aria-expanded=\"true\" aria-controls=\"collapsePathfind\">\n' );
document.write( '        <i class=\"fas fa-fw fa-compass\"></i>\n' );
document.write( '        <span>Pathfinding Algorithms</span>\n' );
document.write( '      </a>\n' );
document.write( '      <div id=\"collapsePathfind\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\n' );
document.write( '        <div class=\"bg-white py-2 collapse-inner rounded\">\n' );
document.write( '           <!-- <h6 class=\"collapse-header\">Custom Components:</h6>  -->\n' );
document.write( '          <a class=\"collapse-item\" href=\"pathfinding/blank.html\">Dijkstra</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"pathfinding/blank.html\">A* Search</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"pathfinding/blank.html\">DFS</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"pathfinding/blank.html\">BFS</a>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <!-- Divider -->\n' );
document.write( '    <hr class=\"sidebar-divider\">\n' );
document.write( '\n' );
document.write( '    <!-- Heading -->\n' );
document.write( '    <div class=\"sidebar-heading\">\n' );
document.write( '      Tutorials for building the site\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <!-- Nav Item - Pages Collapse Menu -->\n' );
document.write( '    <li class=\"nav-item\">\n' );
document.write( '      <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseTwo\" aria-expanded=\"true\" aria-controls=\"collapseTwo\">\n' );
document.write( '        <i class=\"fas fa-fw fa-cog\"></i>\n' );
document.write( '        <span>Components</span>\n' );
document.write( '      </a>\n' );
document.write( '      <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\n' );
document.write( '        <div class=\"bg-white py-2 collapse-inner rounded\">\n' );
document.write( '          <h6 class=\"collapse-header\">Custom Components:</h6>\n' );
document.write( '          <a class=\"collapse-item\" href=\"buttons.html\">Buttons</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"cards.html\">Cards</a>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <!-- Nav Item - Utilities Collapse Menu -->\n' );
document.write( '    <li class=\"nav-item\">\n' );
document.write( '      <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseUtilities\" aria-expanded=\"true\" aria-controls=\"collapseUtilities\">\n' );
document.write( '        <i class=\"fas fa-fw fa-wrench\"></i>\n' );
document.write( '        <span>Utilities</span>\n' );
document.write( '      </a>\n' );
document.write( '      <div id=\"collapseUtilities\" class=\"collapse\" aria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\n' );
document.write( '        <div class=\"bg-white py-2 collapse-inner rounded\">\n' );
document.write( '          <h6 class=\"collapse-header\">Custom Utilities:</h6>\n' );
document.write( '          <a class=\"collapse-item\" href=\"utilities-color.html\">Colors</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"utilities-border.html\">Borders</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"utilities-animation.html\">Animations</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"utilities-other.html\">Other</a>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <!-- Divider -->\n' );
document.write( '    <hr class=\"sidebar-divider\">\n' );
document.write( '\n' );
document.write( '    <!-- Heading -->\n' );
document.write( '    <div class=\"sidebar-heading\">\n' );
document.write( '      Addons\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <!-- Nav Item - Pages Collapse Menu -->\n' );
document.write( '    <li class=\"nav-item\">\n' );
document.write( '      <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePages\" aria-expanded=\"true\" aria-controls=\"collapsePages\">\n' );
document.write( '        <i class=\"fas fa-fw fa-folder\"></i>\n' );
document.write( '        <span>Pages</span>\n' );
document.write( '      </a>\n' );
document.write( '      <div id=\"collapsePages\" class=\"collapse\" aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\n' );
document.write( '        <div class=\"bg-white py-2 collapse-inner rounded\">\n' );
document.write( '          <h6 class=\"collapse-header\">Login Screens:</h6>\n' );
document.write( '          <a class=\"collapse-item\" href=\"login.html\">Login</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"register.html\">Register</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"forgot-password.html\">Forgot Password</a>\n' );
document.write( '          <div class=\"collapse-divider\"></div>\n' );
document.write( '          <h6 class=\"collapse-header\">Other Pages:</h6>\n' );
document.write( '          <a class=\"collapse-item\" href=\"404.html\">404 Page</a>\n' );
document.write( '          <a class=\"collapse-item\" href=\"blank.html\">Blank Page</a>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <!-- Nav Item - Charts -->\n' );
document.write( '    <li class=\"nav-item\">\n' );
document.write( '      <a class=\"nav-link\" href=\"charts.html\">\n' );
document.write( '        <i class=\"fas fa-fw fa-chart-area\"></i>\n' );
document.write( '        <span>Charts</span></a>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <!-- Nav Item - Tables -->\n' );
document.write( '    <li class=\"nav-item\">\n' );
document.write( '      <a class=\"nav-link\" href=\"tables.html\">\n' );
document.write( '        <i class=\"fas fa-fw fa-table\"></i>\n' );
document.write( '        <span>Tables</span></a>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <!-- Divider -->\n' );
document.write( '    <hr class=\"sidebar-divider d-none d-md-block\">\n' );
document.write( '\n' );
document.write( '    <!-- Sidebar Toggler (Sidebar) -->\n' );
document.write( '    <div class=\"text-center d-none d-md-inline\">\n' );
document.write( '      <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '  </ul>\n' );
document.write( '  <!-- End of Sidebar -->' );
